#!/bin/bash

# Function to remove a package
uninstall() {
    package_name="$1"
    sudo xbps-remove -v $package_name
}

# Function to update all installed packages
update() {
    sudo xbps-install -Su
}

check() {
    if [[ $? == 16 ]]; then 
        sudo xbps-install -Su xbps
        sudo xbps-install -Suv
    fi
}

# Function to install a package
install_package() {
    package_name="$1"
    sudo xbps-install -S $package_name
}

cache() {
    echo -e "[ Clearing chache ]"
    sudo xbps-remove -Ov
}

orphans() {
    echo -e "[ Removing orphans ]"
    sudo xbps-remove -ov
}

kernel() {
    echo -e "[ Purging old kernels ]"
    sudo vkpurge rm all
}

search() {
    package_name="$1"
    xbps-query -Rs "$package_name"
}

restart() {
    echo -e "[ Restarting Updated Services ]"
    xcheckrestart
    if [[ $? == 127 ]]; then
        echo -e "To restart updated services you need to have xtools installed"
    fi
}



# Main script
case "$1" in
    remove)
        remove_package "$2"
        ;;
    update)
        echo -e "[ Updating system ]"
        update
        check "$?"

        echo -e ""
        cache
        
        echo -e ""
        orphans

        echo -e ""
        restart 

        ;;
    install)
        install_package "$2"
        ;;
    search)
        search "$2"
        ;;
    kernel)
        kernel
        ;;
    *)
        echo "Usage: $0 [remove | install] <package_name> | update | kernel"
        exit 1
        ;;
esac


